Fixed pendulum version conflict
Pinned pendulum==2.1.2, same as in data-science-dags.

  File "/home/$USER/_git_/elife/data-pipeline/data-hub-core-airflow-dags/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 24, in <module>
    from airflow import settings
  File "/home/$USER/_git_/elife/data-pipeline/data-hub-core-airflow-dags/venv/lib/python3.8/site-packages/airflow/settings.py", line 51, in <module>
    TIMEZONE = pendulum.tz.timezone("UTC")
TypeError: 'module' object is not callable